// Shared ESLint flat config (ARCHITECTURE §3: typescript-eslint + react-hooks).
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';

export default tseslint.config(
  {
    // docs/design is a vendored design import (not project source); the rest are build output.
    ignores: [
      '**/dist/**',
      '**/.turbo/**',
      '**/node_modules/**',
      '**/coverage/**',
      'docs/design/**',
      '.claude/**',
      // sw.ts runs in WebWorker scope; typechecked by tsconfig.worker.json, not the app project.
      '**/sw.ts',
      // Generated by `supabase gen types` (§8.2). It is the committed DB contract, not
      // hand-authored source, and its shape is guarded by the CI `db-types` staleness gate —
      // linting it only flags codegen idioms we don't control.
      '**/database.types.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
      },
    },
    rules: {
      // No `any` (ARCHITECTURE §3).
      '@typescript-eslint/no-explicit-any': 'error',
    },
  },
  {
    files: ['**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks },
    rules: reactHooks.configs.recommended.rules,
  },
  // DEC-19 import boundary: a `modules/*` may not import another `modules/*`. Modules stay
  // independently code-splittable; cross-module sharing goes through packages (§4). One
  // override per module — patterns block both the sibling dir and its barrel.
  {
    files: ['**/modules/patient/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              // Relative specifiers reaching the sibling module (e.g. `../doctor/routes/...`).
              group: ['**/doctor', '**/doctor/**'],
              message: 'DEC-19: modules/patient may not import modules/doctor — share via a package.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['**/modules/doctor/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              // Relative specifiers reaching the sibling module (e.g. `../patient/routes/...`).
              group: ['**/patient', '**/patient/**'],
              message: 'DEC-19: modules/doctor may not import modules/patient — share via a package.',
            },
          ],
        },
      ],
    },
  },
  // Config files run in Node without a project; disable type-aware linting there.
  {
    files: ['**/*.config.{js,ts}', '**/vite.base.ts'],
    ...tseslint.configs.disableTypeChecked,
  },
  // Test files are excluded from the build tsconfig (vitest owns them), so the type-aware
  // project service can't resolve them — lint them without type-checked rules.
  {
    files: ['**/*.test.{ts,tsx}'],
    ...tseslint.configs.disableTypeChecked,
  },
);
