-- =============================================================================
-- P1.1 — Data platform: schema + tenant isolation (RLS)
-- ARCHITECTURE §8.2 (schema), §8.3 (RLS policy matrix = "the tenancy contract"),
-- §9 (multi-tenancy). PRD §6.4 (13-table column list). DEC-14 (one open consult
-- per patient per hospital).
--
-- Discipline (ARCHITECTURE §8.2): forward-only. Every table enables RLS with
-- default-deny in this same migration; policies below are ADDITIVE grants.
--
-- ROLLBACK NOTE: this is the initial schema migration. To roll back, drop the
-- public tables/enum/functions/views created here (reverse dependency order:
-- views → policies → tables → functions → enum → extensions). No prior state to
-- restore. Do not edit this file once applied; supersede with a new numbered
-- migration.
-- =============================================================================

-- Extensions ------------------------------------------------------------------
create extension if not exists pgcrypto;      -- gen_random_uuid()

-- Consult status enum (ARCHITECTURE §8.2 / §8.4 state machine) -----------------
-- Transitions are enforced by a DB trigger in P1.2; here we only define the type.
create type public.consult_status as enum (
  'active',
  'pending_review',
  'approved',
  'rejected',
  'escalated',
  'communicated',
  'closed',
  'superseded',
  'abandoned',
  'expired'
);

-- =============================================================================
-- Tables (PRD §6.4). All PKs uuid default gen_random_uuid(); all timestamps
-- timestamptz default now() (ARCHITECTURE §8.2). RLS enabled default-deny
-- immediately after each CREATE.
-- =============================================================================

-- 1. hospitals — the tenant (ARCHITECTURE §9). Per-hospital config = theme +
--    ai_config only.
create table public.hospitals (
  id         uuid primary key default gen_random_uuid(),
  slug       text unique not null,
  name       text not null,
  logo_url   text,
  theme      jsonb not null default '{}'::jsonb,
  ai_config  jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.hospitals enable row level security;

-- 2. profiles — one row per auth user; id == auth.users.id.
create table public.profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  full_name  text,
  role       text not null default 'patient' check (role in ('patient','doctor','admin')),
  created_at timestamptz not null default now()
);
alter table public.profiles enable row level security;

-- 3. memberships — staff ↔ hospital (operator-provisioned; no self-signup).
create table public.memberships (
  id          uuid primary key default gen_random_uuid(),
  profile_id  uuid not null references public.profiles(id) on delete cascade,
  hospital_id uuid not null references public.hospitals(id) on delete cascade,
  role        text not null default 'doctor' check (role in ('doctor','admin')),
  created_at  timestamptz not null default now(),
  unique (profile_id, hospital_id)
);
alter table public.memberships enable row level security;

-- 4. patient_details — profile-scoped medical record (profile_id is the PK).
create table public.patient_details (
  profile_id  uuid primary key references public.profiles(id) on delete cascade,
  dob         date,
  sex         text,
  blood_group text,
  allergies   jsonb not null default '[]'::jsonb,
  conditions  jsonb not null default '[]'::jsonb,
  medications jsonb not null default '[]'::jsonb,
  updated_at  timestamptz not null default now()
);
alter table public.patient_details enable row level security;

-- 5. consults — the unit of work. status enum incl. abandoned/expired.
create table public.consults (
  id             uuid primary key default gen_random_uuid(),
  hospital_id    uuid not null references public.hospitals(id) on delete cascade,
  patient_id     uuid not null references public.profiles(id) on delete cascade,
  status         public.consult_status not null default 'active',
  chief_complaint text,
  urgency        text,
  ai_confidence  numeric,
  ai_flags       jsonb not null default '[]'::jsonb,
  created_at     timestamptz not null default now(),
  submitted_at   timestamptz
);
alter table public.consults enable row level security;

-- 6. consult_messages — patient ↔ AI intake turns.
create table public.consult_messages (
  id         uuid primary key default gen_random_uuid(),
  consult_id uuid not null references public.consults(id) on delete cascade,
  sender     text not null check (sender in ('patient','ai')),
  content    text,
  ai_note    text,
  created_at timestamptz not null default now()
);
alter table public.consult_messages enable row level security;

-- 7. review_messages — doctor ↔ AI during review (never seen by patient).
create table public.review_messages (
  id         uuid primary key default gen_random_uuid(),
  consult_id uuid not null references public.consults(id) on delete cascade,
  doctor_id  uuid not null references public.profiles(id) on delete cascade,
  sender     text not null check (sender in ('doctor','ai')),
  content    text,
  citations  jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.review_messages enable row level security;

-- 8. ai_drafts — AI recommendation payloads (written only by the edge fn).
create table public.ai_drafts (
  id             uuid primary key default gen_random_uuid(),
  consult_id     uuid not null references public.consults(id) on delete cascade,
  raw_response   jsonb,
  recommendation jsonb,
  created_at     timestamptz not null default now()
);
alter table public.ai_drafts enable row level security;

-- 9. prescriptions — approved output. supersedes_id self-FK (§8.2); a superseding
--    insert flips the prior consult to 'superseded' via the approval RPC (P2+).
create table public.prescriptions (
  id                uuid primary key default gen_random_uuid(),
  consult_id        uuid not null references public.consults(id) on delete cascade,
  hospital_id       uuid not null references public.hospitals(id) on delete cascade,
  patient_id        uuid not null references public.profiles(id) on delete cascade,
  doctor_id         uuid not null references public.profiles(id) on delete cascade,
  items             jsonb not null default '[]'::jsonb,
  advice            text,
  edited_from_draft boolean not null default false,
  supersedes_id     uuid references public.prescriptions(id) on delete set null,
  approved_at       timestamptz not null default now()
);
alter table public.prescriptions enable row level security;

-- 10. reviews — the doctor's decision record for a consult.
create table public.reviews (
  id         uuid primary key default gen_random_uuid(),
  consult_id uuid not null references public.consults(id) on delete cascade,
  doctor_id  uuid not null references public.profiles(id) on delete cascade,
  action     text not null check (action in ('approved','edited','rejected','escalated')),
  reason     text,
  diff       jsonb,
  created_at timestamptz not null default now()
);
alter table public.reviews enable row level security;

-- 11. mira_feedback — doctor corrections that tune the agent (per hospital).
create table public.mira_feedback (
  id         uuid primary key default gen_random_uuid(),
  hospital_id uuid not null references public.hospitals(id) on delete cascade,
  doctor_id  uuid not null references public.profiles(id) on delete cascade,
  consult_id uuid references public.consults(id) on delete set null,
  feedback   text,
  category   text not null check (category in ('correction','style','protocol')),
  created_at timestamptz not null default now()
);
alter table public.mira_feedback enable row level security;

-- 12. consult_media — patient-uploaded images/video for a consult.
create table public.consult_media (
  id           uuid primary key default gen_random_uuid(),
  consult_id   uuid not null references public.consults(id) on delete cascade,
  kind         text not null check (kind in ('image','video')),
  storage_path text not null,
  ai_findings  jsonb,
  created_at   timestamptz not null default now()
);
alter table public.consult_media enable row level security;

-- 13. consult_events — append-only lifecycle log (ARCHITECTURE §8.2/§8.5).
--     Only the service role / SQL triggers write here; append-only for ALL
--     (enforced by a no-mutate trigger below, not merely by absent grants).
create table public.consult_events (
  id          uuid primary key default gen_random_uuid(),
  consult_id  uuid not null references public.consults(id) on delete cascade,
  hospital_id uuid not null references public.hospitals(id) on delete cascade,
  event_type  text not null check (event_type in
                ('status_change','queued','doctor_opened','notification_sent',
                 'sla_escalated','expired','system')),
  actor       text not null check (actor in ('patient','ai','doctor','system')),
  actor_id    uuid,
  payload     jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now()
);
alter table public.consult_events enable row level security;

-- Append-only enforcement: reject UPDATE/DELETE from anyone, incl. service role.
create or replace function public.consult_events_append_only()
returns trigger
language plpgsql
as $$
begin
  raise exception 'consult_events is append-only (% not permitted)', tg_op;
end;
$$;

create trigger consult_events_no_mutate
  before update or delete on public.consult_events
  for each row execute function public.consult_events_append_only();

-- =============================================================================
-- Tenancy helper functions (SECURITY DEFINER: bypass RLS to avoid policy
-- recursion when a policy needs to consult memberships/profiles). Defined after
-- the tables they reference so the SQL bodies validate at creation time.
-- =============================================================================

-- Is the current user a staff member of hospital `h`?
create or replace function public.is_member(h uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.memberships m
    where m.profile_id = auth.uid() and m.hospital_id = h
  );
$$;

-- The current user's platform role ('patient' | 'doctor' | 'admin' | null).
create or replace function public.current_role_of()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select p.role from public.profiles p where p.id = auth.uid();
$$;

-- =============================================================================
-- Indexes (ARCHITECTURE §8.2 MVP set + DEC-14 partial unique index).
-- =============================================================================
create index consults_hospital_status_created_idx
  on public.consults (hospital_id, status, created_at desc);
create index consults_patient_created_idx
  on public.consults (patient_id, created_at desc);
create index consult_messages_consult_created_idx
  on public.consult_messages (consult_id, created_at);
create index consult_events_consult_created_idx
  on public.consult_events (consult_id, created_at);
create index prescriptions_patient_idx
  on public.prescriptions (patient_id);
create index memberships_profile_hospital_idx
  on public.memberships (profile_id, hospital_id);

-- DEC-14: at most one OPEN consult per patient per hospital.
create unique index consults_one_open_per_patient_hospital_idx
  on public.consults (patient_id, hospital_id)
  where status in ('active','pending_review');

-- =============================================================================
-- Public branding view — anon-visible hospital fields for subdomain resolution
-- (ARCHITECTURE §8.3: hospitals "read id,slug,name,logo_url,theme" via a view).
-- =============================================================================
create view public.hospital_public
  with (security_invoker = false) as
  select id, slug, name, logo_url, theme
  from public.hospitals;

-- =============================================================================
-- RLS POLICIES — additive grants per ARCHITECTURE §8.3. Anything not granted
-- here is denied (RLS is enabled on every table above). The service_role used
-- by edge functions bypasses RLS entirely ("all" column of the matrix).
-- =============================================================================

-- hospitals -------------------------------------------------------------------
-- Doctors read hospitals they are a member of. Patients read branding via the
-- hospital_public view (granted below). Edge fn = service role (bypasses RLS).
create policy hospitals_doctor_read on public.hospitals
  for select to authenticated
  using (public.is_member(id));

-- profiles --------------------------------------------------------------------
-- Own row read/write (first-run wizard writes here).
create policy profiles_self_select on public.profiles
  for select to authenticated using (id = auth.uid());
create policy profiles_self_insert on public.profiles
  for insert to authenticated with check (id = auth.uid());
create policy profiles_self_update on public.profiles
  for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

-- memberships -----------------------------------------------------------------
-- Staff read their own memberships. Writes are operator-provisioned (service
-- role only) — no authenticated insert/update/delete policy.
create policy memberships_self_select on public.memberships
  for select to authenticated using (profile_id = auth.uid());

-- patient_details -------------------------------------------------------------
-- Patient owns their row (r/w). Doctor reads details of patients who have a
-- consult in the doctor's hospital.
create policy pd_owner_select on public.patient_details
  for select to authenticated using (profile_id = auth.uid());
create policy pd_owner_insert on public.patient_details
  for insert to authenticated with check (profile_id = auth.uid());
create policy pd_owner_update on public.patient_details
  for update to authenticated using (profile_id = auth.uid()) with check (profile_id = auth.uid());
create policy pd_doctor_select on public.patient_details
  for select to authenticated
  using (exists (
    select 1 from public.consults c
    where c.patient_id = patient_details.profile_id and public.is_member(c.hospital_id)
  ));

-- consults --------------------------------------------------------------------
-- Patient reads own consults and inserts own (into their chosen hospital).
-- Doctor r/w consults where hospital_id ∈ their memberships.
create policy consults_patient_select on public.consults
  for select to authenticated using (patient_id = auth.uid());
create policy consults_patient_insert on public.consults
  for insert to authenticated with check (patient_id = auth.uid());
create policy consults_doctor_select on public.consults
  for select to authenticated using (public.is_member(hospital_id));
create policy consults_doctor_update on public.consults
  for update to authenticated
  using (public.is_member(hospital_id)) with check (public.is_member(hospital_id));

-- consult_messages ------------------------------------------------------------
-- Patient reads messages of own consults and may INSERT PATIENT TURNS ONLY.
-- Doctor reads messages for consults in their hospital.
create policy cm_patient_select on public.consult_messages
  for select to authenticated
  using (exists (
    select 1 from public.consults c
    where c.id = consult_messages.consult_id and c.patient_id = auth.uid()
  ));
create policy cm_patient_insert on public.consult_messages
  for insert to authenticated
  with check (
    sender = 'patient'
    and exists (
      select 1 from public.consults c
      where c.id = consult_messages.consult_id and c.patient_id = auth.uid()
    )
  );
create policy cm_doctor_select on public.consult_messages
  for select to authenticated
  using (exists (
    select 1 from public.consults c
    where c.id = consult_messages.consult_id and public.is_member(c.hospital_id)
  ));

-- review_messages -------------------------------------------------------------
-- Doctor-only, scoped to their hospital (patients never see these).
create policy rm_doctor_select on public.review_messages
  for select to authenticated
  using (exists (
    select 1 from public.consults c
    where c.id = review_messages.consult_id and public.is_member(c.hospital_id)
  ));
create policy rm_doctor_insert on public.review_messages
  for insert to authenticated
  with check (
    doctor_id = auth.uid()
    and exists (
      select 1 from public.consults c
      where c.id = review_messages.consult_id and public.is_member(c.hospital_id)
    )
  );

-- ai_drafts -------------------------------------------------------------------
-- Only the edge fn (service role) WRITES drafts. Patient reads drafts of own
-- consult; doctor reads drafts for their hospital. (Patient summary-only
-- projection is enforced by a patient-facing view / the consult_trace summary
-- field in P1.2; no drafts exist until Phase 2, so the base grant is scoped to
-- own consult here.)
create policy drafts_patient_select on public.ai_drafts
  for select to authenticated
  using (exists (
    select 1 from public.consults c
    where c.id = ai_drafts.consult_id and c.patient_id = auth.uid()
  ));
create policy drafts_doctor_select on public.ai_drafts
  for select to authenticated
  using (exists (
    select 1 from public.consults c
    where c.id = ai_drafts.consult_id and public.is_member(c.hospital_id)
  ));

-- prescriptions ---------------------------------------------------------------
-- Patient reads own; doctor reads own hospital. INSERT is via approval RPCs
-- only (service role / SECURITY DEFINER) — no authenticated insert policy.
create policy rx_patient_select on public.prescriptions
  for select to authenticated using (patient_id = auth.uid());
create policy rx_doctor_select on public.prescriptions
  for select to authenticated using (public.is_member(hospital_id));

-- reviews ---------------------------------------------------------------------
-- Doctor-only, own hospital insert/read.
create policy reviews_doctor_select on public.reviews
  for select to authenticated
  using (exists (
    select 1 from public.consults c
    where c.id = reviews.consult_id and public.is_member(c.hospital_id)
  ));
create policy reviews_doctor_insert on public.reviews
  for insert to authenticated
  with check (
    doctor_id = auth.uid()
    and exists (
      select 1 from public.consults c
      where c.id = reviews.consult_id and public.is_member(c.hospital_id)
    )
  );

-- mira_feedback ---------------------------------------------------------------
-- Doctor-only, own hospital insert/read.
create policy mf_doctor_select on public.mira_feedback
  for select to authenticated using (public.is_member(hospital_id));
create policy mf_doctor_insert on public.mira_feedback
  for insert to authenticated
  with check (doctor_id = auth.uid() and public.is_member(hospital_id));

-- consult_media ---------------------------------------------------------------
-- Patient r/w (upload) for own consults; doctor reads for their hospital.
create policy media_patient_select on public.consult_media
  for select to authenticated
  using (exists (
    select 1 from public.consults c
    where c.id = consult_media.consult_id and c.patient_id = auth.uid()
  ));
create policy media_patient_insert on public.consult_media
  for insert to authenticated
  with check (exists (
    select 1 from public.consults c
    where c.id = consult_media.consult_id and c.patient_id = auth.uid()
  ));
create policy media_doctor_select on public.consult_media
  for select to authenticated
  using (exists (
    select 1 from public.consults c
    where c.id = consult_media.consult_id and public.is_member(c.hospital_id)
  ));

-- consult_events --------------------------------------------------------------
-- Doctor reads events for their hospital. No authenticated write policy: only
-- the service role / SQL triggers write (append-only enforced above).
create policy events_doctor_select on public.consult_events
  for select to authenticated using (public.is_member(hospital_id));

-- =============================================================================
-- GRANTS — column/table privileges for the Data API roles. RLS still applies on
-- top of these for `authenticated`. `service_role` is granted broadly (edge fn).
-- =============================================================================

-- Anon + authenticated may read hospital branding via the public view only.
grant select on public.hospital_public to anon, authenticated;

-- authenticated: table privileges (RLS narrows the actual rows/ops).
grant select, insert, update on public.profiles         to authenticated;
grant select                 on public.memberships       to authenticated;
grant select                 on public.hospitals         to authenticated;
grant select, insert, update on public.patient_details   to authenticated;
grant select, insert, update on public.consults          to authenticated;
grant select, insert         on public.consult_messages  to authenticated;
grant select, insert         on public.review_messages   to authenticated;
grant select                 on public.ai_drafts          to authenticated;
grant select                 on public.prescriptions      to authenticated;
grant select, insert         on public.reviews            to authenticated;
grant select, insert         on public.mira_feedback      to authenticated;
grant select, insert         on public.consult_media      to authenticated;
grant select                 on public.consult_events     to authenticated;

-- service_role: full DML on every table (edge functions; bypasses RLS). Note
-- consult_events UPDATE/DELETE are still blocked by the append-only trigger.
grant select, insert, update, delete on all tables in schema public to service_role;

-- Helper functions are callable by authenticated (used inside policies but also
-- safe to call directly).
grant execute on function public.is_member(uuid)      to authenticated, anon;
grant execute on function public.current_role_of()    to authenticated;
